import type { Chat, Message, TelegramSnapshot, User } from "./types";
import { savedMessagesAvatar } from "./savedMessages";
import mediaPreviewUrl from "../../src-tauri/icons/icon.png";

export const mockProfilePhotoUrl = mediaPreviewUrl;

export const tallMediaPreviewUrl = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(`
  <svg xmlns="http://www.w3.org/2000/svg" width="900" height="1800" viewBox="0 0 900 1800">
    <rect width="900" height="1800" fill="#173b4c"/>
    <rect x="70" y="70" width="760" height="1660" rx="48" fill="#ecf3f1"/>
    <rect x="125" y="145" width="650" height="660" rx="28" fill="#2c8f86"/>
    <rect x="125" y="865" width="650" height="54" rx="18" fill="#173b4c"/>
    <rect x="125" y="965" width="520" height="34" rx="14" fill="#89aaa4"/>
    <rect x="125" y="1040" width="610" height="34" rx="14" fill="#89aaa4"/>
    <rect x="125" y="1115" width="475" height="34" rx="14" fill="#89aaa4"/>
  </svg>
`)}`;

export const wideMediaPreviewUrl = `data:image/svg+xml;charset=utf-8,${encodeURIComponent(`
  <svg xmlns="http://www.w3.org/2000/svg" width="1800" height="600" viewBox="0 0 1800 600">
    <rect width="1800" height="600" fill="#173b4c"/>
    <rect x="90" y="70" width="1620" height="460" rx="42" fill="#ecf3f1"/>
    <rect x="155" y="145" width="620" height="310" rx="28" fill="#2c8f86"/>
    <rect x="850" y="170" width="690" height="46" rx="16" fill="#173b4c"/>
    <rect x="850" y="265" width="540" height="32" rx="12" fill="#89aaa4"/>
    <rect x="850" y="335" width="620" height="32" rx="12" fill="#89aaa4"/>
  </svg>
`)}`;

const botQuoteHeader = "📢Itsu Ovelu | イツ オベル 82";
const botQuoteTopics = ["热搜：", "贺子涵", "秦嘉倪", "高三爱情故事", "九门", "24分钟", "蜘蛛侠", "萌小栖", "积石山", "mina"];
const botQuoteBody = botQuoteTopics.join(" ");
const botQuoteText = `${botQuoteHeader}\n${botQuoteBody}`;
const botQuoteOffset = botQuoteHeader.length + 1;
const longQuoteIntro = "引用内容会保持消息正文可读";
const longQuoteBody = Array.from(
  { length: 8 },
  (_, index) => `引用文本第 ${index + 1} 行：这是需要保留的完整上下文。`,
).join("\n");
const longQuoteText = `${longQuoteIntro}\n${longQuoteBody}`;
const longQuoteOffset = longQuoteIntro.length + 1;

const users: User[] = [
  {
    id: "self",
    displayName: "Alex Morgan",
    firstName: "Alex",
    lastName: "Morgan",
    username: "alexmorgan_fardgram",
    phoneNumber: "+1 555 010 0000",
    avatar: { label: "AM", color: "#d16f45" },
    presence: "online",
  },
  {
    id: "u-mia",
    displayName: "Mia Chen",
    firstName: "Mia",
    lastName: "Chen",
    username: "mia_design",
    avatar: { label: "MC", color: "#397a78" },
    presence: "online",
  },
  {
    id: "u-chen",
    displayName: "David Chen",
    avatar: { label: "DC", color: "#75579a" },
    presence: "offline",
    lastSeenLabel: "30 minutes ago",
  },
  {
    id: "u-jules",
    displayName: "Jules",
    avatar: { label: "J", color: "#3f6e9d" },
    presence: "typing",
  },
  {
    id: "u-fardgram-bot",
    displayName: "Fardgram Bot",
    username: "fardgram_bot",
    avatar: { label: "NB", color: "#4675a8" },
    presence: "online",
    isBot: true,
  },
  {
    id: "u-qa-bot",
    displayName: "QA Helper Bot",
    username: "qa_helper_bot",
    avatar: { label: "QH", color: "#b76a3a" },
    presence: "online",
    isBot: true,
  },
];

const chats: Chat[] = [
  {
    id: "chat-product",
    kind: "group",
    canPinMessages: true,
    folderIds: ["main", "folder:work"],
    title: "Product Discussion",
    avatar: { label: "PD", color: "#207d75" },
    preview: "I updated the interactive spec to the latest version",
    previewSenderId: "u-jules",
    updatedAt: "2026-08-01T09:48:00+08:00",
    unreadCount: 3,
    unreadMentionCount: 0,
    lastReadInboxMessageId: "p-tall",
    pinned: true,
    pinnedFolderIds: ["main", "folder:work"],
    listOrderByFolder: { main: "200", "folder:work": "200" },
    muted: false,
    messageAutoDeleteTime: 0,
  },
  {
    id: "chat-forum",
    kind: "group",
    canPinMessages: false,
    isForum: true,
    canCreateTopics: true,
    folderIds: ["main", "folder:work"],
    title: "Fardgram Forum",
    avatar: { label: "FF", color: "#397a78" },
    preview: "Build & Release · Windows installer verified",
    previewSenderId: "u-jules",
    updatedAt: "2026-08-01T09:46:00+08:00",
    unreadCount: 4,
    unreadMentionCount: 2,
    pinned: false,
    muted: false,
  },
  {
    id: "chat-mia",
    kind: "direct",
    folderIds: ["main"],
    title: "Mia Chen",
    avatar: { label: "MC", color: "#397a78" },
    peerId: "u-mia",
    preview: "Let's sync up on the details at 3 PM",
    previewSenderId: "u-mia",
    updatedAt: "2026-08-01T09:32:00+08:00",
    unreadCount: 1,
    unreadMentionCount: 0,
    lastReadInboxMessageId: "m-2",
    pinned: true,
    pinnedFolderIds: ["main"],
    listOrderByFolder: { main: "100" },
    muted: false,
  },
  {
    id: "chat-saved",
    kind: "saved",
    folderIds: ["main"],
    title: "Saved Messages",
    avatar: savedMessagesAvatar(),
    preview: "TDLib integration notes.md",
    previewSenderId: "self",
    updatedAt: "2026-08-01T08:15:00+08:00",
    unreadCount: 0,
    unreadMentionCount: 0,
    pinned: false,
    muted: false,
  },
  {
    id: "chat-chen",
    kind: "direct",
    folderIds: ["main"],
    title: "David Chen",
    avatar: { label: "DC", color: "#75579a" },
    peerId: "u-chen",
    preview: "Got it, I'll review it tonight",
    previewSenderId: "u-chen",
    updatedAt: "2026-07-31T22:40:00+08:00",
    unreadCount: 0,
    unreadMentionCount: 0,
    lastReadInboxMessageId: "c-old-25",
    pinned: false,
    muted: true,
  },
  {
    id: "chat-release",
    kind: "channel",
    canPinMessages: false,
    folderIds: ["main", "folder:work"],
    title: "Release Notes",
    avatar: { label: "R", color: "#b76a3a" },
    preview: "Desktop build 0.8.4 is ready",
    previewSenderId: "chat:chat-release",
    updatedAt: "2026-07-31T18:06:00+08:00",
    unreadCount: 8,
    unreadMentionCount: 0,
    pinned: false,
    muted: true,
  },
  {
    id: "chat-archive",
    kind: "group",
    canPinMessages: false,
    folderIds: ["archive"],
    title: "Legacy Project Sync",
    avatar: { label: "LP", color: "#687477" },
    preview: "Please review shared files before archiving",
    previewSenderId: "self",
    updatedAt: "2026-07-23T14:20:00+08:00",
    unreadCount: 0,
    unreadMentionCount: 0,
    pinned: false,
    muted: true,
  },
];

const olderProductMessages: Message[] = Array.from({ length: 36 }, (_, index) => ({
  id: `p-old-${index + 1}`,
  chatId: "chat-product",
  senderId: index % 2 === 0 ? "u-jules" : "self",
  outgoing: index % 2 !== 0,
  sentAt: new Date(Date.UTC(2026, 6, 30, 0, index)).toISOString(),
  delivery: "read",
  content: { kind: "text", text: `产品讨论历史消息 ${index + 1}` },
}));

const olderChenMessages: Message[] = Array.from({ length: 48 }, (_, index) => ({
  id: `c-old-${index + 1}`,
  chatId: "chat-chen",
  senderId: index % 2 === 0 ? "u-chen" : "self",
  outgoing: index % 2 !== 0,
  sentAt: new Date(Date.UTC(2026, 6, 30, 1, index)).toISOString(),
  delivery: "read",
  content: { kind: "text", text: `陈默历史消息 ${index + 1}` },
}));

const messages: Message[] = [
  ...olderProductMessages,
  {
    id: "p-service",
    chatId: "chat-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:17:00+08:00",
    delivery: "read",
    content: { kind: "service", text: "Mia Chen 加入了群聊", memberUserIds: ["u-mia"] },
  },
  {
    id: "p-rich-message",
    chatId: "chat-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:17:30+08:00",
    delivery: "read",
    content: {
      kind: "rich",
      isRtl: false,
      isFull: true,
      text: [
        "今日小贴士",
        "保持专注，也别忘了适当休息。",
        "优先处理最重要的一件事",
        "喝点水，活动一下身体",
        "晚上给自己留一点放松时间",
        "慢一点没关系，持续前进就很好。",
        "输入　5,709 tokens 缓存输入　3,712 tokens 输出　68 tokens",
        "Bot API 10.2",
        "E = mc^2",
        "Status Ready",
        "Advanced details",
      ].join("\n"),
      blocks: [
        { kind: "heading", level: 1, text: [{ text: "今日小贴士" }] },
        { kind: "paragraph", text: [{ text: "保持专注，也别忘了适当休息。" }] },
        {
          kind: "list",
          ordered: false,
          items: [
            {
              blocks: [{ kind: "paragraph", text: [{ text: "优先处理最重要的一件事", bold: true }] }],
              hasCheckbox: false,
              checked: false,
            },
            {
              blocks: [{ kind: "paragraph", text: [{ text: "喝点水，活动一下身体" }] }],
              hasCheckbox: false,
              checked: false,
            },
            {
              blocks: [{ kind: "paragraph", text: [{ text: "晚上给自己留一点放松时间" }] }],
              hasCheckbox: false,
              checked: false,
            },
          ],
        },
        {
          kind: "quote",
          pull: false,
          blocks: [{ kind: "paragraph", text: [{ text: "慢一点没关系，持续前进就很好。" }] }],
        },
        {
          kind: "quote",
          pull: false,
          blocks: [{
            kind: "paragraph",
            text: [
              { text: "输入", bold: true },
              { text: "　" },
              { text: "5,709 tokens", code: true },
              { text: " 缓存输入", bold: true },
              { text: "　" },
              { text: "3,712 tokens", code: true },
              { text: " 输出", bold: true },
              { text: "　" },
              { text: "68 tokens", code: true },
            ],
          }],
        },
        {
          kind: "paragraph",
          text: [
            { text: "", anchor: { kind: "anchor", name: "bot-api" } },
            { text: "Bot API 10.2", marked: true },
            { text: " ✨", customEmojiId: "5368324170671202286" },
            { text: " jump", linkTarget: { kind: "anchor", name: "bot-api" } },
          ],
        },
        { kind: "mathematicalExpression", expression: "E = mc^2" },
        {
          kind: "table",
          caption: [{ text: "Status" }],
          bordered: true,
          striped: true,
          rows: [[
            {
              text: [{ text: "Metric", bold: true }],
              header: true,
              colspan: 1,
              rowspan: 1,
              visible: true,
              align: "left",
              valign: "middle",
            },
            {
              text: [{ text: "Ready", spoiler: true }],
              header: false,
              colspan: 1,
              rowspan: 1,
              visible: true,
              align: "center",
              valign: "middle",
            },
          ]],
        },
        {
          kind: "details",
          summary: [{ text: "Advanced" }],
          blocks: [{ kind: "paragraph", text: [{ text: "Advanced details" }] }],
          open: false,
        },
        {
          kind: "media",
          media: {
            mediaType: "photo",
            fileName: "Bot chart",
            sizeLabel: "18 KB",
            localPath: "/mock-video-poster.jpg",
            isDownloaded: true,
            hasSpoiler: false,
            autoplay: false,
            loop: false,
            width: 640,
            height: 360,
            caption: { text: [{ text: "Rich media block" }] },
          },
        },
      ],
    },
  },
  {
    id: "p-unknown",
    chatId: "chat-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:17:45+08:00",
    delivery: "read",
    content: {
      kind: "unsupported",
      type: "messageFutureType",
      text: "收到新类型消息（messageFutureType）",
    },
  },
  {
    id: "p-1",
    chatId: "chat-product",
    senderId: "u-jules",
    outgoing: false,
    sentAt: "2026-08-01T09:18:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "早上好，左侧会话列表的密度已经调整好了。" },
  },
  {
    id: "p-2",
    chatId: "chat-product",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-08-01T09:24:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "看到了。消息区再留一点呼吸感，信息密度就比较平衡。" },
  },
  {
    id: "p-3",
    chatId: "chat-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:35:00+08:00",
    delivery: "read",
    content: {
      kind: "file",
      fileName: "desktop-layout-review.pdf",
      sizeLabel: "2.4 MB",
      fileId: 42,
      size: 2_516_582,
      localPath: "/mock-file.pdf",
      canDownload: false,
      isDownloading: false,
      isDownloaded: true,
    },
  },
  {
    id: "p-file-downloading",
    chatId: "chat-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:36:00+08:00",
    delivery: "read",
    content: {
      kind: "file",
      fileName: "research-notes.zip",
      sizeLabel: "12.8 MB",
      fileId: 43,
      size: 13_421_772,
      canDownload: true,
      isDownloading: true,
      isDownloaded: false,
      progress: 0.48,
    },
  },
  {
    id: "p-4",
    chatId: "chat-product",
    senderId: "u-jules",
    outgoing: false,
    sentAt: "2026-08-01T09:48:00+08:00",
    delivery: "read",
    isPinned: true,
    content: { kind: "text", text: "我把交互稿更新到最新版本了，下午可以直接走查。" },
  },
  {
    id: "p-channel-reply",
    chatId: "chat-product",
    senderId: "chat:chat-release",
    outgoing: false,
    sentAt: "2026-08-01T09:48:10+08:00",
    delivery: "read",
    forwardInfo: {
      origin: { kind: "channel", chatId: "chat-release", messageId: "release-post-1", authorSignature: "Release editor" },
      source: {
        chatId: "chat-release",
        messageId: "release-post-1",
        senderId: "chat:chat-release",
        outgoing: false,
      },
    },
    interaction: { viewCount: 22_200, forwardCount: 23, replyCount: 0, reactions: [] },
    replyTo: {
      kind: "message",
      chatId: "chat-product",
      messageId: "p-old-8",
      content: { kind: "text", text: "产品讨论历史消息 8" },
    },
    content: { kind: "text", text: "Release Notes channel posted this reply" },
  },
  {
    id: "p-markdown",
    chatId: "chat-product",
    senderId: "u-jules",
    outgoing: false,
    sentAt: "2026-08-01T09:48:20+08:00",
    delivery: "read",
    content: {
      kind: "text",
      text: "**Markdown 粗体**、*斜体*、~~删除线~~\n\n- 支持列表\n- 支持 `code` 与 [链接](https://t.me/mia_design)",
    },
  },
  {
    id: "p-rich-entities",
    chatId: "chat-product",
    senderId: "u-jules",
    outgoing: false,
    sentAt: "2026-08-01T09:48:40+08:00",
    delivery: "read",
    content: {
      kind: "text",
      text: "TDLib bold link @mia_design @fardgram_bot #release",
      entities: [
        { offset: 6, length: 4, kind: "bold" },
        { offset: 11, length: 4, kind: "textUrl", href: "https://t.me/addtheme/FardgramTheme" },
        { offset: 16, length: 11, kind: "mention" },
        { offset: 28, length: 12, kind: "mention" },
        { offset: 41, length: 8, kind: "hashtag" },
      ],
    },
  },
  {
    id: "p-bot-keyboard",
    chatId: "chat-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:48:50+08:00",
    delivery: "read",
    content: { kind: "text", text: "请选择内容分类或翻页" },
    replyMarkup: {
      kind: "inlineKeyboard",
      rows: [
        ["👥", "📢", "🎬", "🏞", "🎧", "💬", "🤖", "📁"].map((text, index) => ({
          kind: "callback" as const,
          style: "default" as const,
          text,
          data: `Y2F0ZWdvcnk9${index}`,
        })),
        [
          { kind: "callback", style: "default", text: "🆕最新", data: "bGF0ZXN0" },
          { kind: "callback", style: "default", text: "🔞过滤", data: "ZmlsdGVy" },
          { kind: "callback", style: "primary", text: "下一页", data: "cGFnZT0y" },
        ],
      ],
    },
  },
  {
    id: "p-tall",
    chatId: "chat-product",
    mediaAlbumId: "mock-album-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:49:00+08:00",
    delivery: "read",
    content: {
      kind: "media",
      mediaType: "photo",
      fileName: "纵向图片.jpg",
      sizeLabel: "220 KB",
      dataCenterId: 4,
      remoteId: "AwADBAADewAPKgQ",
      previewDataUrl: tallMediaPreviewUrl,
      width: 512,
      height: 512,
      caption: "纵向图片应该按实际比例收窄，外壳不能留下额外空白。",
      isDownloaded: false,
      isDownloading: false,
    },
  },
  {
    id: "p-5",
    chatId: "chat-product",
    mediaAlbumId: "mock-album-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:50:00+08:00",
    delivery: "read",
    content: {
      kind: "media",
      mediaType: "photo",
      fileName: "界面预览.jpg",
      sizeLabel: "186 KB",
      dataCenterId: 2,
      remoteId: "AwADAgADewAPKgQ",
      previewDataUrl: mediaPreviewUrl,
      width: 512,
      height: 512,
      caption: "新的媒体预览样式",
      isDownloaded: false,
      isDownloading: true,
      progress: 0.62,
    },
  },
  {
    id: "p-video",
    chatId: "chat-product",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-08-01T09:51:00+08:00",
    delivery: "read",
    content: {
      kind: "media",
      mediaType: "video",
      fileName: "交互预览.mp4",
      sizeLabel: "278 KB",
      fileId: 93,
      size: 283_989,
      mimeType: "video/mp4",
      previewDataUrl: "/mock-video-poster.jpg",
      width: 640,
      height: 360,
      caption: "这是昨晚导出的交互录屏，麻烦确认最后一段。",
      captionEntities: [{ offset: 2, length: 2, kind: "bold" }],
      canDownload: true,
      isDownloaded: false,
      isDownloading: false,
    },
  },
  {
    id: "p-audio",
    chatId: "chat-product",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-08-01T09:50:30+08:00",
    delivery: "read",
    content: {
      kind: "media",
      mediaType: "voice",
      fileName: "产品语音.m4a",
      sizeLabel: "278 KB",
      fileId: 94,
      size: 283_989,
      mimeType: "audio/mp4",
      localPath: "/mock-video.mp4",
      canDownload: true,
      isDownloaded: true,
      isDownloading: false,
    },
  },
  {
    id: "p-audio-next",
    chatId: "chat-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:50:40+08:00",
    delivery: "read",
    content: {
      kind: "media",
      mediaType: "audio",
      fileName: "评审跟进.m4a",
      sizeLabel: "196 KB",
      fileId: 95,
      size: 200_704,
      mimeType: "audio/mp4",
      localPath: "/mock-video.mp4",
      duration: 18,
      canDownload: true,
      isDownloaded: true,
      isDownloading: false,
    },
  },
  {
    id: "p-poll",
    chatId: "chat-product",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:50:45+08:00",
    delivery: "read",
    content: {
      kind: "poll",
      pollId: "mock-poll-product",
      question: "下一轮优先验证哪一项？",
      options: [
        {
          id: "native-media",
          position: 0,
          text: "原生媒体发送",
          voterCount: 6,
          votePercentage: 60,
          chosen: false,
          beingChosen: false,
          correct: false,
        },
        {
          id: "offline-outbox",
          position: 1,
          text: "附件离线发件箱",
          voterCount: 4,
          votePercentage: 40,
          chosen: false,
          beingChosen: false,
          correct: false,
        },
      ],
      totalVoterCount: 10,
      type: "regular",
      allowsMultipleAnswers: false,
      allowsRevoting: true,
      isAnonymous: false,
      isClosed: false,
      canSeeResults: false,
    },
  },
  {
    id: "m-1",
    chatId: "chat-mia",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:10:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "登录流程先覆盖手机号、验证码和二步验证，对吗？" },
  },
  {
    id: "m-2",
    chatId: "chat-mia",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-08-01T09:20:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "对，QR 登录放在下一轮，不影响主链路。" },
  },
  {
    id: "m-tall-caption",
    chatId: "chat-mia",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:25:00+08:00",
    delivery: "read",
    content: {
      kind: "media",
      mediaType: "photo",
      fileName: "频道长图.jpg",
      sizeLabel: "420 KB",
      previewDataUrl: tallMediaPreviewUrl,
      width: 900,
      height: 1800,
      caption: "看到公众号发了一个有趣的小活动，我们也来玩玩吧。",
      isDownloaded: false,
      isDownloading: false,
    },
  },
  {
    id: "m-wide-caption",
    chatId: "chat-mia",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:26:00+08:00",
    delivery: "read",
    content: {
      kind: "media",
      mediaType: "photo",
      fileName: "横向预览.jpg",
      sizeLabel: "310 KB",
      previewDataUrl: wideMediaPreviewUrl,
      width: 1800,
      height: 600,
      caption: "短说明",
      isDownloaded: false,
      isDownloading: false,
    },
  },
  {
    id: "m-3",
    chatId: "chat-mia",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:32:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "那我们下午三点对一下细节。" },
  },
  {
    id: "saved-long-quote",
    chatId: "chat-saved",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-08-01T08:14:00+08:00",
    delivery: "read",
    content: {
      kind: "text",
      text: longQuoteText,
      entities: [
        { offset: longQuoteOffset, length: longQuoteBody.length, kind: "blockquote" },
      ],
    },
  },
  {
    id: "s-2",
    chatId: "chat-saved",
    senderId: "self",
    outgoing: false,
    sentAt: "2026-08-01T08:16:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "收藏夹方向测试" },
  },
  {
    id: "s-1",
    chatId: "chat-saved",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-08-01T08:15:00+08:00",
    delivery: "read",
    content: {
      kind: "file",
      fileName: "TDLib integration notes.md",
      sizeLabel: "18 KB",
    },
  },
  {
    id: "archive-bot-quote",
    chatId: "chat-archive",
    senderId: "u-mia",
    senderTag: "热点机器人",
    outgoing: false,
    sentAt: "2026-07-23T14:20:00+08:00",
    delivery: "read",
    content: {
      kind: "text",
      text: botQuoteText,
      entities: [
        { offset: botQuoteOffset, length: botQuoteBody.length, kind: "blockquote" },
        ...botQuoteTopics.map((topic, index) => ({
          offset: botQuoteText.indexOf(topic, botQuoteOffset),
          length: topic.length,
          kind: "textUrl" as const,
          href: `https://t.me/jisou1Bot?start=topic_${index}`,
        })),
      ],
    },
  },
  ...olderChenMessages,
  {
    id: "c-1",
    chatId: "chat-chen",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-07-31T22:35:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "原生桥接接口我先按事件流来设计。" },
  },
  {
    id: "c-2",
    chatId: "chat-chen",
    senderId: "u-chen",
    outgoing: false,
    sentAt: "2026-07-31T22:40:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "收到，我今晚看一下。" },
  },
  {
    id: "product-thread-1",
    chatId: "chat-product",
    topicId: "42",
    senderId: "u-jules",
    outgoing: false,
    sentAt: "2026-08-01T09:47:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "群组线程消息也应显示在主会话中。" },
  },
  {
    id: "release-post-1",
    chatId: "chat-release",
    senderId: "chat:chat-release",
    authorSignature: "Release editor",
    isChannelPost: true,
    outgoing: false,
    sentAt: "2026-08-01T09:48:10+08:00",
    delivery: "read",
    interaction: { viewCount: 22_200, forwardCount: 23, replyCount: 2, reactions: [], hasDiscussion: true },
    content: { kind: "text", text: "Release Notes channel posted this reply" },
  },
  {
    id: "release-comment-1",
    chatId: "chat-release",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:49:10+08:00",
    delivery: "read",
    replyTo: {
      kind: "message",
      chatId: "chat-release",
      messageId: "release-post-1",
      content: { kind: "text", text: "Release Notes channel posted this reply" },
    },
    content: { kind: "text", text: "这个版本的桌面端体验顺滑了很多。" },
  },
  {
    id: "release-comment-2",
    chatId: "chat-release",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-08-01T09:50:02+08:00",
    delivery: "read",
    replyTo: {
      kind: "message",
      chatId: "chat-release",
      messageId: "release-post-1",
      content: { kind: "text", text: "Release Notes channel posted this reply" },
    },
    content: { kind: "text", text: "谢谢反馈，我们会继续收集问题。" },
  },
  {
    id: "forum-general-1",
    chatId: "chat-forum",
    topicId: "1",
    senderId: "u-mia",
    outgoing: false,
    sentAt: "2026-08-01T09:12:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "欢迎来到 Fardgram 论坛，公告和常见问题放在这里。" },
  },
  {
    id: "forum-release-1",
    chatId: "chat-forum",
    topicId: "12",
    senderId: "u-jules",
    outgoing: false,
    sentAt: "2026-08-01T09:46:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "Windows 安装包已验证，欢迎反馈升级问题。" },
  },
  {
    id: "forum-design-1",
    chatId: "chat-forum",
    topicId: "18",
    senderId: "self",
    outgoing: true,
    sentAt: "2026-07-31T16:20:00+08:00",
    delivery: "read",
    content: { kind: "text", text: "我整理了话题导航的交互草案。" },
  },
];

export const mockSnapshot: TelegramSnapshot = {
  currentUserId: "self",
  authorization: { kind: "ready" },
  users,
  folders: [
    { id: "main", title: "All Chats", iconName: "All" },
    { id: "folder:work", title: "Work", iconName: "Custom" },
    { id: "archive", title: "Archive", iconName: "Archive" },
  ],
  chats: chats.map(chat => ({ ...chat, canDeleteForSelf: chat.kind === "direct",
    canDeleteForAllUsers: chat.kind === "direct" && !users.find(user => user.id === chat.peerId)?.isBot,
    isBlocked: false, ...((chat.kind === "group" || chat.kind === "channel") ? { isMember: true } : {}) })),
  messages,
};
