import type { AgentProviderId, AgentProviderPreset } from "./types";

export const AGENT_PROVIDERS: Record<AgentProviderId, AgentProviderPreset> = {
  gemini: {
    id: "gemini",
    name: "Google Gemini",
    badge: "Official & Recommended",
    tagline: "Ultra-fast inference with massive context window up to 1M+ tokens",
    description: "Google's state-of-the-art models via the official OpenAI-compatible endpoint. Ideal for analyzing entire chat histories.",
    defaultEndpoint: "https://generativelanguage.googleapis.com/v1beta/openai",
    defaultModel: "gemini-2.5-flash",
    models: [
      { id: "gemini-2.5-flash", name: "Gemini 2.5 Flash", description: "Flagship speed & accuracy, great for chat digestion & tasks", isDefault: true, contextWindow: "1M tokens" },
      { id: "gemini-2.5-pro", name: "Gemini 2.5 Pro", description: "Complex multi-step reasoning and deep content forensics", contextWindow: "1M tokens" },
      { id: "gemini-2.0-flash", name: "Gemini 2.0 Flash", description: "Lowest latency with native tool execution", contextWindow: "1M tokens" },
      { id: "gemini-1.5-pro", name: "Gemini 1.5 Pro", description: "Massive context retention and high fidelity", contextWindow: "2M tokens" },
    ],
    requiresKey: true,
    apiKeyHelpUrl: "https://aistudio.google.com/app/apikey",
    docsUrl: "https://ai.google.dev/gemini-api/docs",
    iconName: "Sparkles",
  },
  openai: {
    id: "openai",
    name: "OpenAI",
    badge: "Industry Standard",
    tagline: "GPT-4o and o3-mini reasoning models with robust tool calling",
    description: "Industry-leading models with premier function calling capabilities and reliable structured outputs.",
    defaultEndpoint: "https://api.openai.com/v1",
    defaultModel: "gpt-4o",
    models: [
      { id: "gpt-4o", name: "GPT-4o", description: "Flagship omni model with high intelligence and tool reliability", isDefault: true, contextWindow: "128k tokens" },
      { id: "gpt-4o-mini", name: "GPT-4o Mini", description: "Fast, cost-efficient model for everyday chat tasks", contextWindow: "128k tokens" },
      { id: "o3-mini", name: "o3-mini", description: "Fast reasoning model specialized in logic and deep analysis", contextWindow: "200k tokens" },
      { id: "o1", name: "o1", description: "Maximum reasoning capability for difficult analytical tasks", contextWindow: "200k tokens" },
    ],
    requiresKey: true,
    apiKeyHelpUrl: "https://platform.openai.com/api-keys",
    docsUrl: "https://platform.openai.com/docs",
    iconName: "Cpu",
  },
  claude: {
    id: "claude",
    name: "Anthropic Claude",
    badge: "Premier Intelligence",
    tagline: "Nuanced writing, empathetic tone and unmatched analytical depth",
    description: "World-class models known for superior understanding, nuanced phrasing, and high safety.",
    defaultEndpoint: "https://api.anthropic.com/v1",
    defaultModel: "claude-3-7-sonnet",
    models: [
      { id: "claude-3-7-sonnet", name: "Claude 3.7 Sonnet", description: "Hybrid reasoning with instant or deep thinking modes", isDefault: true, contextWindow: "200k tokens" },
      { id: "claude-3-5-sonnet", name: "Claude 3.5 Sonnet", description: "Exceptional coding, document summarization and detail", contextWindow: "200k tokens" },
      { id: "claude-3-5-haiku", name: "Claude 3.5 Haiku", description: "Ultra-fast lightweight model for instant replies", contextWindow: "200k tokens" },
    ],
    requiresKey: true,
    apiKeyHelpUrl: "https://console.anthropic.com/settings/keys",
    docsUrl: "https://docs.anthropic.com",
    iconName: "Feather",
  },
  openrouter: {
    id: "openrouter",
    name: "OpenRouter",
    badge: "All-in-One Gateway",
    tagline: "Single API key to access Claude, Gemini, GPT, DeepSeek, and 200+ models",
    description: "Unified aggregator providing instant access to all AI models without maintaining separate accounts.",
    defaultEndpoint: "https://openrouter.ai/api/v1",
    defaultModel: "auto",
    models: [
      { id: "auto", name: "Auto Router (Best Model)", description: "Dynamically picks the best model for the prompt", isDefault: true },
      { id: "anthropic/claude-3.5-sonnet", name: "Claude 3.5 Sonnet (OpenRouter)", description: "Anthropic's flagship via OpenRouter" },
      { id: "google/gemini-2.5-flash", name: "Gemini 2.5 Flash (OpenRouter)", description: "Google's fastest multimodal model" },
      { id: "deepseek/deepseek-r1", name: "DeepSeek R1 (OpenRouter)", description: "Leading open reasoning model" },
      { id: "meta-llama/llama-3.3-70b-instruct", name: "Llama 3.3 70B (OpenRouter)", description: "Meta's flagship open-weights model" },
    ],
    requiresKey: true,
    apiKeyHelpUrl: "https://openrouter.ai/keys",
    docsUrl: "https://openrouter.ai/docs",
    iconName: "Globe",
  },
  groq: {
    id: "groq",
    name: "Groq Cloud",
    badge: "Ultra Low Latency",
    tagline: "500+ tokens per second powered by LPUs",
    description: "The fastest LLM inference on the planet. Real-time typing and instant conversation replies.",
    defaultEndpoint: "https://api.groq.com/openai/v1",
    defaultModel: "llama-3.3-70b-versatile",
    models: [
      { id: "llama-3.3-70b-versatile", name: "Llama 3.3 70B Versatile", description: "Blazing fast 70B model with full tool calling", isDefault: true, contextWindow: "128k tokens" },
      { id: "deepseek-r1-distill-llama-70b", name: "DeepSeek R1 Distill 70B", description: "Deep reasoning at extreme Groq speed", contextWindow: "128k tokens" },
      { id: "mixtral-8x7b-32768", name: "Mixtral 8x7B", description: "Fast MoE model for text tasks", contextWindow: "32k tokens" },
    ],
    requiresKey: true,
    apiKeyHelpUrl: "https://console.groq.com/keys",
    docsUrl: "https://console.groq.com/docs",
    iconName: "Zap",
  },
  deepseek: {
    id: "deepseek",
    name: "DeepSeek",
    badge: "Reasoning & Value",
    tagline: "State of the art open reasoning and chat models",
    description: "Highly affordable, powerful frontier models featuring DeepSeek-V3 and DeepSeek-R1 reasoning.",
    defaultEndpoint: "https://api.deepseek.com",
    defaultModel: "deepseek-chat",
    models: [
      { id: "deepseek-chat", name: "DeepSeek V3 (Chat)", description: "General conversation, high reasoning and multilingual", isDefault: true, contextWindow: "64k tokens" },
      { id: "deepseek-reasoner", name: "DeepSeek R1 (Reasoner)", description: "Chain-of-thought mathematical and logic reasoning", contextWindow: "64k tokens" },
    ],
    requiresKey: true,
    apiKeyHelpUrl: "https://platform.deepseek.com/api_keys",
    docsUrl: "https://api-docs.deepseek.com",
    iconName: "BrainCircuit",
  },
  mistral: {
    id: "mistral",
    name: "Mistral AI",
    badge: "European Frontier",
    tagline: "Precision reasoning, code parsing and multilingual mastery",
    description: "French AI lab pioneer providing top-tier models with strong multilingual support.",
    defaultEndpoint: "https://api.mistral.ai/v1",
    defaultModel: "mistral-large-latest",
    models: [
      { id: "mistral-large-latest", name: "Mistral Large", description: "Flagship model with complex reasoning and native tool use", isDefault: true, contextWindow: "128k tokens" },
      { id: "mistral-small-latest", name: "Mistral Small", description: "Fast, cost-efficient model for summary tasks", contextWindow: "32k tokens" },
      { id: "codestral-latest", name: "Codestral", description: "Specialized model for code, JSON, and structured extraction", contextWindow: "256k tokens" },
    ],
    requiresKey: true,
    apiKeyHelpUrl: "https://console.mistral.ai/api-keys/",
    docsUrl: "https://docs.mistral.ai",
    iconName: "Layers",
  },
  ollama: {
    id: "ollama",
    name: "Ollama (Local / Offline)",
    badge: "100% Private & Free",
    tagline: "Runs completely locally on your hardware with zero external API calls",
    description: "No internet required, no API key needed. Your messages and files never leave your machine.",
    defaultEndpoint: "http://localhost:11434/v1",
    defaultModel: "llama3.2",
    models: [
      { id: "llama3.2", name: "Llama 3.2 (Meta)", description: "Standard local 3B model, great for fast chat on CPU/GPU", isDefault: true },
      { id: "deepseek-r1:8b", name: "DeepSeek R1 (8B Local)", description: "Local reasoning model running via Ollama" },
      { id: "qwen2.5:7b", name: "Qwen 2.5 (7B)", description: "Exceptional multilingual & Persian language capabilities" },
      { id: "mistral:latest", name: "Mistral (7B)", description: "Balanced local model for instruction following" },
    ],
    requiresKey: false,
    apiKeyHelpUrl: "https://ollama.com",
    docsUrl: "https://github.com/ollama/ollama",
    iconName: "ShieldCheck",
  },
  custom: {
    id: "custom",
    name: "Custom (OpenAI-Compatible)",
    badge: "Self-Hosted / Proxy",
    tagline: "Connect to LM Studio, LocalAI, vLLM, Jan, or any custom API gateway",
    description: "Specify any custom base URL, port, authorization header, and model identifier.",
    defaultEndpoint: "http://127.0.0.1:1234/v1",
    defaultModel: "custom-model",
    models: [
      { id: "custom-model", name: "Custom Model", description: "User specified model name", isDefault: true },
    ],
    requiresKey: false,
    apiKeyHelpUrl: "",
    docsUrl: "",
    iconName: "Sliders",
  },
};
